export { StackNavOutlet } from './lib/outlet';
export type { StackNavView, StackNavRouteRef, StackNavActivation } from './lib/outlet';
export { StackNav } from './lib/stacknav.service';
export type { StackNavExtras } from './lib/stacknav.service';
export { StackNavBack } from './lib/back.directive';
export { StackNavHistory } from './lib/history';
export type { NavigationInfo, StackNavStateHint } from './lib/history';
export { provideStackNav, STACKNAV_CONFIG, defaultKeyOf, defaultLevelOf, resolveConfig } from './lib/config';
export type { StackNavConfig, ResolvedStackNavConfig } from './lib/config';
export { StackNavRouteReuseStrategy } from './lib/route-reuse-strategy';
export { StackNavActivatedRoute } from './lib/activated-route-proxy';
